require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LifequotesController do

  # This should return the minimal set of attributes required to create a valid
  # Lifequote. As you add validations to Lifequote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cover_amount" => "9.99" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LifequotesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lifequotes as @lifequotes" do
      lifequote = Lifequote.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lifequotes).should eq([lifequote])
    end
  end

  describe "GET show" do
    it "assigns the requested lifequote as @lifequote" do
      lifequote = Lifequote.create! valid_attributes
      get :show, {:id => lifequote.to_param}, valid_session
      assigns(:lifequote).should eq(lifequote)
    end
  end

  describe "GET new" do
    it "assigns a new lifequote as @lifequote" do
      get :new, {}, valid_session
      assigns(:lifequote).should be_a_new(Lifequote)
    end
  end

  describe "GET edit" do
    it "assigns the requested lifequote as @lifequote" do
      lifequote = Lifequote.create! valid_attributes
      get :edit, {:id => lifequote.to_param}, valid_session
      assigns(:lifequote).should eq(lifequote)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lifequote" do
        expect {
          post :create, {:lifequote => valid_attributes}, valid_session
        }.to change(Lifequote, :count).by(1)
      end

      it "assigns a newly created lifequote as @lifequote" do
        post :create, {:lifequote => valid_attributes}, valid_session
        assigns(:lifequote).should be_a(Lifequote)
        assigns(:lifequote).should be_persisted
      end

      it "redirects to the created lifequote" do
        post :create, {:lifequote => valid_attributes}, valid_session
        response.should redirect_to(Lifequote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lifequote as @lifequote" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lifequote.any_instance.stub(:save).and_return(false)
        post :create, {:lifequote => { "cover_amount" => "invalid value" }}, valid_session
        assigns(:lifequote).should be_a_new(Lifequote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lifequote.any_instance.stub(:save).and_return(false)
        post :create, {:lifequote => { "cover_amount" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lifequote" do
        lifequote = Lifequote.create! valid_attributes
        # Assuming there are no other lifequotes in the database, this
        # specifies that the Lifequote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lifequote.any_instance.should_receive(:update).with({ "cover_amount" => "9.99" })
        put :update, {:id => lifequote.to_param, :lifequote => { "cover_amount" => "9.99" }}, valid_session
      end

      it "assigns the requested lifequote as @lifequote" do
        lifequote = Lifequote.create! valid_attributes
        put :update, {:id => lifequote.to_param, :lifequote => valid_attributes}, valid_session
        assigns(:lifequote).should eq(lifequote)
      end

      it "redirects to the lifequote" do
        lifequote = Lifequote.create! valid_attributes
        put :update, {:id => lifequote.to_param, :lifequote => valid_attributes}, valid_session
        response.should redirect_to(lifequote)
      end
    end

    describe "with invalid params" do
      it "assigns the lifequote as @lifequote" do
        lifequote = Lifequote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lifequote.any_instance.stub(:save).and_return(false)
        put :update, {:id => lifequote.to_param, :lifequote => { "cover_amount" => "invalid value" }}, valid_session
        assigns(:lifequote).should eq(lifequote)
      end

      it "re-renders the 'edit' template" do
        lifequote = Lifequote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lifequote.any_instance.stub(:save).and_return(false)
        put :update, {:id => lifequote.to_param, :lifequote => { "cover_amount" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lifequote" do
      lifequote = Lifequote.create! valid_attributes
      expect {
        delete :destroy, {:id => lifequote.to_param}, valid_session
      }.to change(Lifequote, :count).by(-1)
    end

    it "redirects to the lifequotes list" do
      lifequote = Lifequote.create! valid_attributes
      delete :destroy, {:id => lifequote.to_param}, valid_session
      response.should redirect_to(lifequotes_url)
    end
  end

end
